# Generated by Django 5.0.7 on 2024-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('color', models.TextField(max_length=10)),
                ('description', models.TextField(max_length=2000)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
    ]
