# Generated by Django 5.0.7 on 2024-07-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
